import { NextResponse } from 'next/server';
import fs from 'fs/promises';
import path from 'path';
import bcrypt from 'bcryptjs';
import { PrismaClient } from '@prisma/client';
import crypto from 'crypto';

export async function POST(request: Request) {
    try {
        // Check if setup is already complete
        const setupCompletePath = path.join(process.cwd(), '.setup-complete');
        try {
            await fs.access(setupCompletePath);
            return NextResponse.json({ error: 'Kurulum zaten tamamlanmış' }, { status: 403 });
        } catch {
            // File doesn't exist, continue with setup
        }

        const formData = await request.formData();
        const appName = formData.get('appName') as string;
        const themeColor = formData.get('themeColor') as string || 'blue';
        const serverRoot = formData.get('serverRoot') as string;
        const database = formData.get('database') as string;
        const mongoUrl = formData.get('mongoUrl') as string;
        const adminUsername = formData.get('adminUsername') as string;
        const adminPassword = formData.get('adminPassword') as string;
        const logoFile = formData.get('logo') as File | null;

        // Validate inputs
        if (!appName || !serverRoot || !adminUsername || !adminPassword) {
            return NextResponse.json({ error: 'Eksik bilgi' }, { status: 400 });
        }

        // Generate random JWT secret
        const jwtSecret = crypto.randomBytes(64).toString('hex');

        // Create .env file
        const databaseUrl = database === 'mongodb' ? mongoUrl : 'file:./dev.db';
        const envContent = `# Generated by Setup Wizard
DATABASE_URL="${databaseUrl}"
JWT_SECRET="${jwtSecret}"
APP_NAME="${appName}"
THEME_COLOR="${themeColor}"
SERVER_ROOT="${serverRoot.replace(/\\/g, '\\\\')}"
SETUP_COMPLETE="true"
`;

        await fs.writeFile(path.join(process.cwd(), '.env'), envContent, 'utf-8');

        // Create config.json for client-side access
        const configJson = {
            appName,
            themeColor,
            setupComplete: true,
        };
        await fs.writeFile(
            path.join(process.cwd(), 'public', 'config.json'),
            JSON.stringify(configJson, null, 2),
            'utf-8'
        );

        // Configure Prisma based on database choice

        // Configure Prisma based on database choice
        let prismaSchema = `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "${database === 'mongodb' ? 'mongodb' : 'sqlite'}"
  url      = env("DATABASE_URL")
}

model User {
  id          String   @id @default(${database === 'mongodb' ? 'auto()' : 'uuid()'}) ${database === 'mongodb' ? '@map("_id") @db.ObjectId' : ''}
  username    String   @unique
  password    String
  role        String   @default("user")
  isApproved  Boolean  @default(false)
  permissions String   @default("[]")
  createdAt   DateTime @default(now())
}

model AuditLog {
  id        String   @id @default(${database === 'mongodb' ? 'auto()' : 'uuid()'}) ${database === 'mongodb' ? '@map("_id") @db.ObjectId' : ''}
  username  String
  action    String
  details   String?
  timestamp DateTime @default(now())
}`;

        await fs.writeFile(path.join(process.cwd(), 'prisma', 'schema.prisma'), prismaSchema, 'utf-8');


        // Handle logo upload
        if (logoFile) {
            const logoBuffer = Buffer.from(await logoFile.arrayBuffer());
            const logoPath = path.join(process.cwd(), 'public', 'logo.png');
            await fs.writeFile(logoPath, logoBuffer);
        }

        // Run Prisma migrations
        const { exec } = require('child_process');
        const util = require('util');
        const execPromise = util.promisify(exec);

        try {
            await execPromise('npx prisma db push --skip-generate', { cwd: process.cwd() });
        } catch (error) {
            console.error('Prisma migration error:', error);
            // Continue anyway, might be already migrated
        }

        // Create admin user
        const prisma = new PrismaClient();
        const hashedPassword = await bcrypt.hash(adminPassword, 10);

        await prisma.user.create({
            data: {
                username: adminUsername,
                password: hashedPassword,
                role: 'admin',
                isApproved: true,
                permissions: JSON.stringify(['*']), // Admin has all permissions
            },
        });

        await prisma.$disconnect();

        // Create .setup-complete marker
        await fs.writeFile(setupCompletePath, new Date().toISOString(), 'utf-8');

        return NextResponse.json({ success: true });
    } catch (error) {
        console.error('Setup error:', error);
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
}
